require('dotenv').config();

SERVIDORES_DIST = [];
SERVIDORES_DIST['SERVIDOR_A'] = {
    HOST: process.env.SERVIDOR_A_HOST,
    HEARTBEAT_URL: process.env.SERVIDOR_A_HEARTBEAT_URL
}

SERVIDORES_DIST['SERVIDOR_B'] = {
    HOST: process.env.SERVIDOR_B_HOST,
    HEARTBEAT_URL: process.env.SERVIDOR_B_HEARTBEAT_URL
}

SERVIDORES_DIST['SERVIDOR_C'] = {
    HOST: process.env.SERVIDOR_C_HOST,
    HEARTBEAT_URL: process.env.SERVIDOR_C_HEARTBEAT_URL
}

module.exports = {
    PRECIO_KM: 1.5,
    VELOCIDAD_PROMEDIO: 20,
    PRECIO_X_LIBRA: 3,
    ORDEN_PAGADA: "PAGADO",
    ORDEN_NUEVA: "NUEVO",
    EXITOSO: "EXITOSO",
    SERVIDOR_ACTUAL: process.env.SERVIDOR_ACTUAL,
    SERVIDORES_DIST: SERVIDORES_DIST,
    PERCENT_TAX: 0.085
}